[2025-02-18T15:01:08.999+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: etl_pipeline.extract scheduled__2025-02-17T00:00:00+00:00 [queued]>
[2025-02-18T15:01:09.006+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: etl_pipeline.extract scheduled__2025-02-17T00:00:00+00:00 [queued]>
[2025-02-18T15:01:09.007+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-02-18T15:01:09.008+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-02-18T15:01:09.009+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-02-18T15:01:09.020+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): extract> on 2025-02-17 00:00:00+00:00
[2025-02-18T15:01:09.025+0000] {standard_task_runner.py:55} INFO - Started process 545 to run task
[2025-02-18T15:01:09.027+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'extract', 'scheduled__2025-02-17T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpe4gjszsj']
[2025-02-18T15:01:09.029+0000] {standard_task_runner.py:83} INFO - Job 18: Subtask extract
[2025-02-18T15:01:09.043+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-18T15:01:09.064+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-18T15:01:09.104+0000] {task_command.py:388} INFO - Running <TaskInstance: etl_pipeline.extract scheduled__2025-02-17T00:00:00+00:00 [running]> on host bf9eef710f83
[2025-02-18T15:01:09.198+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_pipeline
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2025-02-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-02-17T00:00:00+00:00
[2025-02-18T15:01:09.200+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-02-18T15:01:09.201+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "üîç Iniciando extracci√≥n de datos..." && sleep 2 && echo "‚úÖ Extracci√≥n completada."']
[2025-02-18T15:01:09.213+0000] {subprocess.py:86} INFO - Output:
[2025-02-18T15:01:09.214+0000] {subprocess.py:93} INFO - üîç Iniciando extracci√≥n de datos...
[2025-02-18T15:01:11.216+0000] {subprocess.py:93} INFO - ‚úÖ Extracci√≥n completada.
[2025-02-18T15:01:11.217+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-02-18T15:01:11.248+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=extract, execution_date=20250217T000000, start_date=20250218T150109, end_date=20250218T150111
[2025-02-18T15:01:11.297+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2025-02-18T15:01:11.316+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
